# Basic Tensor Operations

Basic tensor operations using TensorFlow v2.

In [6]:
from __future__ import print_function
import tensorflow as tf

In [7]:
print(f"Tensorflow version installed {tf.__version__}")

Tensorflow version installed 2.10.1


In [8]:
# Create a Tensor.
hello = tf.constant("hello world")
print(hello)

tf.Tensor(b'hello world', shape=(), dtype=string)


In [9]:
# To access a Tensor value, call numpy().
print(hello.numpy())

b'hello world'


In [10]:
# Define tensor constants.
a = tf.constant(2)
b = tf.constant(3)
c = tf.constant(5)

In [11]:
# Various tensor operations.
# Note: Tensors also support python operators (+, *, ...)
add = tf.add(a, b)
sub = tf.subtract(a, b)
mul = tf.multiply(a, b)
div = tf.divide(a, b)

# Access tensors value.
print("add =", add)
print("sub =", sub.numpy())
print("mul =", mul.numpy())
print("div =", div.numpy())

add = tf.Tensor(5, shape=(), dtype=int32)
sub = -1
mul = 6
div = 0.6666666666666666


In [12]:
# Some more operations.
mean = tf.reduce_mean([a, b, c])
sum = tf.reduce_sum([a, b, c])

# Access tensors value.
print("mean =", mean.numpy())
print("sum =", sum.numpy())

mean = 3
sum = 10


In [13]:
# Matrix multiplications.
matrix1 = tf.constant([[1., 2.], [3., 4.]])
matrix2 = tf.constant([[5., 6.], [7., 8.]])

product = tf.matmul(matrix1, matrix2)

In [14]:
# Display Tensor.
product

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[19., 22.],
       [43., 50.]], dtype=float32)>

In [15]:
# Convert Tensor to Numpy.
product.numpy()

array([[19., 22.],
       [43., 50.]], dtype=float32)